---
on: [push]

jobs:

  release:
    runs-on: ubuntu-20.04

    env:
      DOCKER_IMAGE: ghcr.io/kivra/cloudserver
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build Docker image
        shell: 'script -q -e -c "bash {0}"'
        run: docker build -t "${DOCKER_IMAGE}" .

      - name: Publish Docker image
        run: |
          GIT_BRANCH="${GITHUB_REF##*/}"
          GIT_COMMIT="${GITHUB_SHA:0:7}"
          COMMIT_TAG=${GIT_BRANCH}-${GIT_COMMIT}
          echo "Publishing Docker image with latest commit: ${COMMIT_TAG}"
          docker tag "${DOCKER_IMAGE}" "${DOCKER_IMAGE}:${COMMIT_TAG}"
          docker push "${DOCKER_IMAGE}:${COMMIT_TAG}"
